version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html
hooks:
  BeforeInstall:
    - location: /home/ubuntu/pre.sh
      timeout: 300
      runas: root
  AfterInstall:
  ApplicationStart:
  ApplicationStop:
